--------------TABLE SEQUENCE------------------

--TBL_ADDR
--ADDR_NUMBER NUMBER PK
--ADDR_DETAIL VARCHAR2(100) NN
CREATE TABLE TBL_ADDR(
	ADDR_NUMBER VARCHAR2(20)
	,ADDR_DETAIL VARCHAR2(100) NOT NULL
	,CONSTRAINT ADDR_PK PRIMARY KEY (ADDR_NUMBER)
);

--CREATE SEQUENCE SEQ_ADDR NOCACHE NOCYCLE;

--TBL_USER
--USER_NUMBER NUMBER PK
--========================
--USER_ID VARCHAR2(100) UK, NN
--USER_PW VARCHAR2(100) NN
--USER_NAME VARCHAR2(100) NN
--USER_PHONE VARCHAR2(100) NN
--ADDR_NUMBER NUMBER FK
CREATE TABLE TBL_USER (
	USER_NUMBER NUMBER
	,USER_ID VARCHAR2(100) NOT NULL
	,USER_PW VARCHAR2(100) NOT NULL
	,USER_NAME VARCHAR2(100) NOT NULL
	,USER_PHONE VARCHAR2(100) NOT NULL 
	,ADDR_NUMBER NUMBER 
	,CONSTRAINT USER_PK PRIMARY KEY (USER_NUMBER)
	,CONSTRAINT USER_ID_UK UNIQUE (USER_ID)
	,CONSTRAINT USER_ADDR_FK FOREIGN KEY (ADDR_NUMBER) REFERENCES TBL_ADDR(ADDR_NUMBER)
);

CREATE SEQUENCE SEQ_USER NOCACHE NOCYCLE;

--TBL_ITEM
--ITEM_NUMBER NUMBER PK
--========================
--ITEM_NAME VARCHAR2(100) NN
--ITEM_CAT VARCHAR2(100) CHECK, NN
--ITEM_PRICE NUMBER DEFAULT 0, NN
--ITEM_STOCK NUMBER DEFAULT 0, NN
CREATE TABLE TBL_ITEM (
	ITEM_NUMBER NUMBER
	,ITEM_NAME VARCHAR2(100) NOT NULL
	,ITEM_CAT VARCHAR2(100) CHECK(ITEM_CAT IN('모자', '상의', '하의', '신발')) NOT NULL
	,ITEM_PRICE NUMBER DEFAULT 0 NOT NULL 
	,ITEM_STOCK NUMBER DEFAULT 0 NOT NULL 
	,CONSTRAINT ITEM_PK PRIMARY KEY (ITEM_NUMBER)
);

CREATE SEQUENCE SEQ_ITEM NOCACHE NOCYCLE;

--TBL_ORDER
--ORDER_NUMBER NUMBER PK
--=========================
--ORDER_DATE DATE NN
--ORDER_STATE VARCHAR2(100) CHECK, NN
--USER_NUMBER NUMBER FK
--ITEM_NUMBER NUMBER FK
--ADDR_NUMBER NUMBER FK
CREATE TABLE TBL_ORDER (
	ORDER_NUMBER NUMBER 
	,ORDER_DATE DATE NOT NULL
	,ORDER_STATUS VARCHAR2(100) CHECK(ORDER_STATUS IN ('주문불가','상품준비중','배송중','배송완료'))  NOT NULL
	,USER_NUMBER NUMBER 
	,ITEM_NUMBER NUMBER
	,ADDR_NUMBER NUMBER
	,CONSTRAINT ORDER_PK PRIMARY KEY(ORDER_NUMBER)
	,CONSTRAINT ORDER_USER_FK FOREIGN KEY (USER_NUMBER) REFERENCES TBL_USER (USER_NUMBER)
	,CONSTRAINT ORDER_ITEM_FK FOREIGN KEY (ITEM_NUMBER) REFERENCES TBL_ITEM (ITEM_NUMBER)
	,CONSTRAINT ORDER_ADDR_FK FOREIGN KEY (ADDR_NUMBER) REFERENCES TBL_ADDR (ADDR_NUMBER)
);

CREATE SEQUENCE SEQ_ORDER NOCACHE NOCYCLE;


SELECT * FROM TBL_ADDR;
SELECT * FROM TBL_USER;
SELECT * FROM TBL_ITEM;
SELECT * FROM TBL_ORDER;

----------DATA--------------------

