DROP TABLE TBL_ADDR;

--TBL_ADDR
--ADDR_NUMBER NUMBER PK
--ADDR_DETAIL VARCHAR2(100) NN
CREATE TABLE TBL_ADDR(
	ADDR_NUMBER VARCHAR2(20)
	,ADDR_DETAIL VARCHAR2(100) NOT NULL
	,CONSTRAINT ADDR_PK PRIMARY KEY (ADDR_NUMBER)
);

DROP TABLE TBL_USER;

--TBL_USER
--USER_NUMBER NUMBER PK
--========================
--USER_ID VARCHAR2(100) UK, NN
--USER_PW VARCHAR2(100) NN
--USER_NAME VARCHAR2(100) NN
--USER_PHONE VARCHAR2(100) NN
--ADDR_NUMBER NUMBER FK
CREATE TABLE TBL_USER (
	USER_NUMBER NUMBER
	,USER_ID VARCHAR2(100) NOT NULL
	,USER_PW VARCHAR2(100) NOT NULL
	,USER_NAME VARCHAR2(100) NOT NULL
	,USER_PHONE VARCHAR2(100) NOT NULL 
	,ADDR_NUMBER VARCHAR(20) 
	,CONSTRAINT USER_PK PRIMARY KEY (USER_NUMBER)
	,CONSTRAINT USER_ID_UK UNIQUE (USER_ID)
	,CONSTRAINT USER_ADDR_FK FOREIGN KEY (ADDR_NUMBER) REFERENCES TBL_ADDR(ADDR_NUMBER)
);

DROP SEQUENCE SEQ_USER;

CREATE SEQUENCE SEQ_USER NOCACHE NOCYCLE;

DROP TABLE TBL_ITEM;

--TBL_ITEM
--ITEM_NUMBER NUMBER PK
--========================
--ITEM_NAME VARCHAR2(100) NN
--ITEM_CAT VARCHAR2(100) CHECK, NN
--ITEM_PRICE NUMBER DEFAULT 0, NN
--ITEM_STOCK NUMBER DEFAULT 0, NN
CREATE TABLE TBL_ITEM (
	ITEM_NUMBER NUMBER
	,ITEM_NAME VARCHAR2(100) NOT NULL
	,ITEM_CAT VARCHAR2(100) CHECK(ITEM_CAT IN('모자', '상의', '하의', '신발')) NOT NULL
	,ITEM_PRICE NUMBER DEFAULT 0 NOT NULL 
	,ITEM_STOCK NUMBER DEFAULT 0 NOT NULL 
	,CONSTRAINT ITEM_PK PRIMARY KEY (ITEM_NUMBER)
);

DROP SEQUENCE SEQ_ITEM;

CREATE SEQUENCE SEQ_ITEM NOCACHE NOCYCLE;

DROP TABLE TBL_ORDER;

--TBL_ORDER
--ORDER_NUMBER NUMBER PK
--=========================
--ORDER_DATE DATE NN
--ORDER_STATE VARCHAR2(100) CHECK, NN
--USER_NUMBER NUMBER FK
--ITEM_NUMBER NUMBER FK
--ADDR_NUMBER NUMBER FK

CREATE TABLE TBL_ORDER (
	ORDER_NUMBER NUMBER 
	,ORDER_DATE DATE NOT NULL
	,ORDER_STATUS VARCHAR2(100) CHECK(ORDER_STATUS IN ('주문불가','상품준비중','배송중','배송완료'))  NOT NULL
	,USER_NUMBER NUMBER 
	,ITEM_NUMBER NUMBER
	,ADDR_NUMBER VARCHAR(20)
	,CONSTRAINT ORDER_PK PRIMARY KEY(ORDER_NUMBER)
	,CONSTRAINT ORDER_USER_FK FOREIGN KEY (USER_NUMBER) REFERENCES TBL_USER (USER_NUMBER)
	,CONSTRAINT ORDER_ITEM_FK FOREIGN KEY (ITEM_NUMBER) REFERENCES TBL_ITEM (ITEM_NUMBER)
	,CONSTRAINT ORDER_ADDR_FK FOREIGN KEY (ADDR_NUMBER) REFERENCES TBL_ADDR (ADDR_NUMBER)
);

DROP SEQUENCE SEQ_ORDER;

CREATE SEQUENCE SEQ_ORDER NOCACHE NOCYCLE;


SELECT * FROM TBL_ADDR;
SELECT * FROM TBL_USER;
SELECT * FROM TBL_ITEM;
SELECT * FROM TBL_ORDER;


INSERT INTO TBL_ADDR
VALUES ('08758','서울특별시 관악구 남부순환로');
INSERT INTO TBL_ADDR
VALUES ('06035','서울특별시 강남구 강남대로');
INSERT INTO TBL_ADDR
VALUES ('03322','서울특별시 은평구 갈현로');
INSERT INTO TBL_ADDR
VALUES ('06972', '서울특별시 동작구 노량진로');
INSERT INTO TBL_ADDR
VALUES ('06236', '서울특별시 강남구 테헤란로');
INSERT INTO TBL_ADDR
VALUES ('01002', '서울특별시 강북구 도선사길');
INSERT INTO TBL_ADDR
VALUES ('04733', '서울특별시 성동구 독서당로');

INSERT INTO TBL_ITEM 
VALUES(SEQ_ORDER.NEXTVAL, 'Red_Cap', '모자', 80000, 10);
INSERT INTO TBL_ITEM 
VALUES(SEQ_ORDER.NEXTVAL, 'Blu_Cap', '모자', 75000, 10);
INSERT INTO TBL_ITEM 
VALUES(SEQ_ORDER.NEXTVAL, 'Blk_Cap', '모자', 80000, 10);

INSERT INTO TBL_ITEM 
VALUES(SEQ_ORDER.NEXTVAL, 'Blk_Knit', '상의', 120000, 10);
INSERT INTO TBL_ITEM 
VALUES(SEQ_ORDER.NEXTVAL, 'Gry_Knit', '상의', 200000, 10);
INSERT INTO TBL_ITEM 
VALUES(SEQ_ORDER.NEXTVAL, 'Blk_Coat', '상의', 200000, 10);

INSERT INTO TBL_ITEM 
VALUES(SEQ_ORDER.NEXTVAL, 'Blk_Denim', '하의', 82000, 10);
INSERT INTO TBL_ITEM 
VALUES(SEQ_ORDER.NEXTVAL, 'Wht_Chino', '하의', 90000, 10);
INSERT INTO TBL_ITEM 
VALUES(SEQ_ORDER.NEXTVAL, 'Bei_Chino', '하의', 90000, 10);

INSERT INTO TBL_ITEM 
VALUES(SEQ_ORDER.NEXTVAL, 'Bei_Shoes', '신발', 72000, 10);
INSERT INTO TBL_ITEM 
VALUES(SEQ_ORDER.NEXTVAL, 'Yel_Shoes', '신발', 80000, 10);
INSERT INTO TBL_ITEM 
VALUES(SEQ_ORDER.NEXTVAL, 'Gry_Shoes', '신발', 80000, 10);

-- 테스트용 유저 테이블 데이터 삽입
--INSERT INTO TBL_USER (USER_NUMBER,USER_ID,USER_PW,USER_NAME,ADDR_NUMBER)
--VALUES(SEQ_USER.NEXTVAL,'gu1234','1234','짱구','010-1234-1234','08758');
--
-- 테스트용 주문 테이블 데이터 삽입
--INSERT INTO TBL_ORDER(ORDER_NUMBER,ORDER_DATE, ORDER_STATUS, USER_NUMBER,ITEM_NUMBER, ADDR_NUMBER) 
--VALUES(SEQ_ORDER.NEXTVAL, to_date('2026-01-31','yyyy-mm-dd'),'배송중',1,34,'08758');
--INSERT INTO TBL_ORDER 
--VALUES(SEQ_ORDER.NEXTVAL, to_date('2026-02-01','yyyy-mm-dd'),'배송중',1,36,'08758');
--INSERT INTO TBL_ORDER 
--VALUES(SEQ_ORDER.NEXTVAL,  TRUNC (SYSDATE),'상품준비중',1,44,'08758');